"""postgres workspace baseline

Revision ID: 20260613_0001
Revises:
Create Date: 2026-06-13 19:43:36.434568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260613_0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_user_id'), 'conversation_messages', ['user_id'], unique=False)
    op.create_table('conversation_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=256), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('last_summarized_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('group_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.String(length=256), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_time', sa.Integer(), nullable=False),
    sa.Column('stored_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_messages_chat_id'), 'group_messages', ['chat_id'], unique=False)
    op.create_table('group_webhooks',
    sa.Column('chat_id', sa.String(length=256), nullable=False),
    sa.Column('webhook_url', sa.String(length=1024), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('inbound_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('msgid', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('response_url', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_messages_msgid'), 'inbound_messages', ['msgid'], unique=True)
    op.create_index(op.f('ix_inbound_messages_status'), 'inbound_messages', ['status'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('scope_id', sa.String(length=255), nullable=True),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_documents_checksum', 'knowledge_documents', ['checksum'], unique=False)
    op.create_index('ix_knowledge_documents_scope_domain', 'knowledge_documents', ['scope_type', 'scope_id', 'domain'], unique=False)
    op.create_table('memory_fragments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding_json', sa.Text(), nullable=True),
    sa.Column('signal_strength', sa.Float(), nullable=False),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_fragments_user_id'), 'memory_fragments', ['user_id'], unique=False)
    op.create_table('polls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.String(length=256), nullable=False),
    sa.Column('creator_user_id', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_polls_chat_id'), 'polls', ['chat_id'], unique=False)
    op.create_index(op.f('ix_polls_creator_user_id'), 'polls', ['creator_user_id'], unique=False)
    op.create_table('reminder_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reminder_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('delivered_to', sa.String(length=128), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_runs_reminder_id'), 'reminder_runs', ['reminder_id'], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creator_user_id', sa.String(length=256), nullable=False),
    sa.Column('mention_user_id', sa.String(length=256), nullable=False),
    sa.Column('target_name', sa.String(length=128), nullable=False),
    sa.Column('chat_id', sa.String(length=256), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('schedule_type', sa.String(length=32), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=True),
    sa.Column('cron', sa.String(length=64), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_creator_user_id'), 'reminders', ['creator_user_id'], unique=False)
    op.create_index(op.f('ix_reminders_enabled'), 'reminders', ['enabled'], unique=False)
    op.create_index(op.f('ix_reminders_next_run_at'), 'reminders', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_reminders_status'), 'reminders', ['status'], unique=False)
    op.create_index(op.f('ix_reminders_target_name'), 'reminders', ['target_name'], unique=False)
    op.create_table('user_group_access',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=256), nullable=False),
    sa.Column('group_id', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_id', name='uq_user_group_access')
    )
    op.create_index(op.f('ix_user_group_access_group_id'), 'user_group_access', ['group_id'], unique=False)
    op.create_index(op.f('ix_user_group_access_user_id'), 'user_group_access', ['user_id'], unique=False)
    op.create_table('user_memories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=256), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding_json', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_memories_user_id'), 'user_memories', ['user_id'], unique=False)
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('embedding_json', sa.Text(), nullable=True),
    sa.Column('related_profile_ids', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('decayed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profile_user_id'), 'user_profile', ['user_id'], unique=False)
    op.create_table('wecom_user_bindings',
    sa.Column('open_userid', sa.String(length=256), nullable=False),
    sa.Column('userid', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('open_userid'),
    sa.UniqueConstraint('userid')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('policy', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_status'), 'workspaces', ['status'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('scope_id', sa.String(length=255), nullable=True),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_chunks_document_order', 'knowledge_chunks', ['document_id', 'chunk_index'], unique=False)
    op.create_index('ix_knowledge_chunks_scope_domain', 'knowledge_chunks', ['scope_type', 'scope_id', 'domain'], unique=False)
    op.create_table('poll_votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=256), nullable=False),
    sa.Column('option_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_id', 'user_id')
    )
    op.create_index(op.f('ix_poll_votes_poll_id'), 'poll_votes', ['poll_id'], unique=False)
    op.create_index(op.f('ix_poll_votes_user_id'), 'poll_votes', ['user_id'], unique=False)
    op.create_table('research_tasks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_msgid', sa.String(length=128), nullable=False),
    sa.Column('requester_open_userid', sa.String(length=256), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('research_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('access_scope', sa.JSON(), nullable=False),
    sa.Column('max_rounds', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('current_round', sa.Integer(), nullable=False),
    sa.Column('quality_status', sa.String(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('enqueued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_tasks_requester_open_userid'), 'research_tasks', ['requester_open_userid'], unique=False)
    op.create_index(op.f('ix_research_tasks_source_msgid'), 'research_tasks', ['source_msgid'], unique=True)
    op.create_index(op.f('ix_research_tasks_status'), 'research_tasks', ['status'], unique=False)
    op.create_index('ix_research_tasks_user_status', 'research_tasks', ['requester_open_userid', 'status'], unique=False)
    op.create_index(op.f('ix_research_tasks_workspace_id'), 'research_tasks', ['workspace_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('open_userid', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('research_approved_once', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'open_userid', name='uq_workspace_member_identity')
    )
    op.create_index(op.f('ix_workspace_members_open_userid'), 'workspace_members', ['open_userid'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.create_table('knowledge_chunk_embeddings',
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('vector_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index('ix_knowledge_chunk_embeddings_model', 'knowledge_chunk_embeddings', ['model_name'], unique=False)
    op.create_table('research_deliveries',
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('recipient_userid', sa.String(length=256), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('wecom_msgid', sa.String(length=256), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['research_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_research_deliveries_status'), 'research_deliveries', ['status'], unique=False)
    op.create_index(op.f('ix_research_deliveries_workspace_id'), 'research_deliveries', ['workspace_id'], unique=False)
    op.create_table('research_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('quality_status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['research_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'version', name='uq_research_report_version')
    )
    op.create_index(op.f('ix_research_reports_task_id'), 'research_reports', ['task_id'], unique=False)
    op.create_index(op.f('ix_research_reports_workspace_id'), 'research_reports', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_reports_workspace_id'), table_name='research_reports')
    op.drop_index(op.f('ix_research_reports_task_id'), table_name='research_reports')
    op.drop_table('research_reports')
    op.drop_index(op.f('ix_research_deliveries_workspace_id'), table_name='research_deliveries')
    op.drop_index(op.f('ix_research_deliveries_status'), table_name='research_deliveries')
    op.drop_table('research_deliveries')
    op.drop_index('ix_knowledge_chunk_embeddings_model', table_name='knowledge_chunk_embeddings')
    op.drop_table('knowledge_chunk_embeddings')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_open_userid'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_research_tasks_workspace_id'), table_name='research_tasks')
    op.drop_index('ix_research_tasks_user_status', table_name='research_tasks')
    op.drop_index(op.f('ix_research_tasks_status'), table_name='research_tasks')
    op.drop_index(op.f('ix_research_tasks_source_msgid'), table_name='research_tasks')
    op.drop_index(op.f('ix_research_tasks_requester_open_userid'), table_name='research_tasks')
    op.drop_table('research_tasks')
    op.drop_index(op.f('ix_poll_votes_user_id'), table_name='poll_votes')
    op.drop_index(op.f('ix_poll_votes_poll_id'), table_name='poll_votes')
    op.drop_table('poll_votes')
    op.drop_index('ix_knowledge_chunks_scope_domain', table_name='knowledge_chunks')
    op.drop_index('ix_knowledge_chunks_document_order', table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_workspaces_status'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_table('wecom_user_bindings')
    op.drop_index(op.f('ix_user_profile_user_id'), table_name='user_profile')
    op.drop_table('user_profile')
    op.drop_index(op.f('ix_user_memories_user_id'), table_name='user_memories')
    op.drop_table('user_memories')
    op.drop_index(op.f('ix_user_group_access_user_id'), table_name='user_group_access')
    op.drop_index(op.f('ix_user_group_access_group_id'), table_name='user_group_access')
    op.drop_table('user_group_access')
    op.drop_index(op.f('ix_reminders_target_name'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_status'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_next_run_at'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_enabled'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_creator_user_id'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_reminder_runs_reminder_id'), table_name='reminder_runs')
    op.drop_table('reminder_runs')
    op.drop_index(op.f('ix_polls_creator_user_id'), table_name='polls')
    op.drop_index(op.f('ix_polls_chat_id'), table_name='polls')
    op.drop_table('polls')
    op.drop_index(op.f('ix_memory_fragments_user_id'), table_name='memory_fragments')
    op.drop_table('memory_fragments')
    op.drop_index('ix_knowledge_documents_scope_domain', table_name='knowledge_documents')
    op.drop_index('ix_knowledge_documents_checksum', table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_inbound_messages_status'), table_name='inbound_messages')
    op.drop_index(op.f('ix_inbound_messages_msgid'), table_name='inbound_messages')
    op.drop_table('inbound_messages')
    op.drop_table('group_webhooks')
    op.drop_index(op.f('ix_group_messages_chat_id'), table_name='group_messages')
    op.drop_table('group_messages')
    op.drop_table('conversation_summaries')
    op.drop_index(op.f('ix_conversation_messages_user_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    # ### end Alembic commands ###
