"""add research execution graph

Revision ID: 27dc16205bab
Revises: 511141124e0f
Create Date: 2026-06-13 20:11:59.592812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27dc16205bab'
down_revision: Union[str, Sequence[str], None] = '511141124e0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('step_id', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['research_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_events_event_type'), 'research_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_research_events_step_id'), 'research_events', ['step_id'], unique=False)
    op.create_index(op.f('ix_research_events_task_id'), 'research_events', ['task_id'], unique=False)
    op.create_index(op.f('ix_research_events_workspace_id'), 'research_events', ['workspace_id'], unique=False)
    op.create_table('research_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('completion_criteria', sa.JSON(), nullable=False),
    sa.Column('estimated_cost_microunits', sa.Integer(), nullable=False),
    sa.Column('estimated_tokens', sa.Integer(), nullable=False),
    sa.Column('raw_plan', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['research_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'task_id', 'version', name='uq_research_plan_version')
    )
    op.create_index(op.f('ix_research_plans_task_id'), 'research_plans', ['task_id'], unique=False)
    op.create_index(op.f('ix_research_plans_workspace_id'), 'research_plans', ['workspace_id'], unique=False)
    op.create_table('research_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('step_id', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=256), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_microunits', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['research_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_usage_step_id'), 'research_usage', ['step_id'], unique=False)
    op.create_index(op.f('ix_research_usage_task_id'), 'research_usage', ['task_id'], unique=False)
    op.create_index(op.f('ix_research_usage_workspace_id'), 'research_usage', ['workspace_id'], unique=False)
    op.create_table('research_approvals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('decided_by', sa.String(length=256), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['research_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['research_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_approvals_status'), 'research_approvals', ['status'], unique=False)
    op.create_index(op.f('ix_research_approvals_task_id'), 'research_approvals', ['task_id'], unique=False)
    op.create_index(op.f('ix_research_approvals_workspace_id'), 'research_approvals', ['workspace_id'], unique=False)
    op.create_table('research_steps',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=256), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result_ref', sa.String(length=512), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['research_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['research_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'idempotency_key', name='uq_research_step_idempotency')
    )
    op.create_index('ix_research_steps_claim', 'research_steps', ['status', 'available_at', 'lease_expires_at'], unique=False)
    op.create_index(op.f('ix_research_steps_plan_id'), 'research_steps', ['plan_id'], unique=False)
    op.create_index(op.f('ix_research_steps_status'), 'research_steps', ['status'], unique=False)
    op.create_index(op.f('ix_research_steps_task_id'), 'research_steps', ['task_id'], unique=False)
    op.create_index(op.f('ix_research_steps_workspace_id'), 'research_steps', ['workspace_id'], unique=False)
    op.create_table('research_step_dependencies',
    sa.Column('step_id', sa.String(length=64), nullable=False),
    sa.Column('depends_on_step_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_step_id'], ['research_steps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['research_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('step_id', 'depends_on_step_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('research_step_dependencies')
    op.drop_index(op.f('ix_research_steps_workspace_id'), table_name='research_steps')
    op.drop_index(op.f('ix_research_steps_task_id'), table_name='research_steps')
    op.drop_index(op.f('ix_research_steps_status'), table_name='research_steps')
    op.drop_index(op.f('ix_research_steps_plan_id'), table_name='research_steps')
    op.drop_index('ix_research_steps_claim', table_name='research_steps')
    op.drop_table('research_steps')
    op.drop_index(op.f('ix_research_approvals_workspace_id'), table_name='research_approvals')
    op.drop_index(op.f('ix_research_approvals_task_id'), table_name='research_approvals')
    op.drop_index(op.f('ix_research_approvals_status'), table_name='research_approvals')
    op.drop_table('research_approvals')
    op.drop_index(op.f('ix_research_usage_workspace_id'), table_name='research_usage')
    op.drop_index(op.f('ix_research_usage_task_id'), table_name='research_usage')
    op.drop_index(op.f('ix_research_usage_step_id'), table_name='research_usage')
    op.drop_table('research_usage')
    op.drop_index(op.f('ix_research_plans_workspace_id'), table_name='research_plans')
    op.drop_index(op.f('ix_research_plans_task_id'), table_name='research_plans')
    op.drop_table('research_plans')
    op.drop_index(op.f('ix_research_events_workspace_id'), table_name='research_events')
    op.drop_index(op.f('ix_research_events_task_id'), table_name='research_events')
    op.drop_index(op.f('ix_research_events_step_id'), table_name='research_events')
    op.drop_index(op.f('ix_research_events_event_type'), table_name='research_events')
    op.drop_table('research_events')
    # ### end Alembic commands ###
