"""add research evidence

Revision ID: 2b8ff99750ef
Revises: 27dc16205bab
Create Date: 2026-06-13 20:34:06.345601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b8ff99750ef'
down_revision: Union[str, Sequence[str], None] = '27dc16205bab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('step_id', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_ref', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('publisher', sa.String(length=512), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['research_steps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['research_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'content_hash', name='uq_research_evidence_hash')
    )
    op.create_index(op.f('ix_research_evidence_step_id'), 'research_evidence', ['step_id'], unique=False)
    op.create_index(op.f('ix_research_evidence_task_id'), 'research_evidence', ['task_id'], unique=False)
    op.create_index(op.f('ix_research_evidence_workspace_id'), 'research_evidence', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_evidence_workspace_id'), table_name='research_evidence')
    op.drop_index(op.f('ix_research_evidence_task_id'), table_name='research_evidence')
    op.drop_index(op.f('ix_research_evidence_step_id'), table_name='research_evidence')
    op.drop_table('research_evidence')
    # ### end Alembic commands ###
