"""add research claims and review findings

Revision ID: e57f8e3d7981
Revises: 2b8ff99750ef
Create Date: 2026-06-13 20:51:35.356479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e57f8e3d7981'
down_revision: Union[str, Sequence[str], None] = '2b8ff99750ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_claims',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('claim_key', sa.String(length=128), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.String(length=32), nullable=False),
    sa.Column('material', sa.Boolean(), nullable=False),
    sa.Column('validation_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['research_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['research_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_claims_report_id'), 'research_claims', ['report_id'], unique=False)
    op.create_index(op.f('ix_research_claims_task_id'), 'research_claims', ['task_id'], unique=False)
    op.create_index(op.f('ix_research_claims_workspace_id'), 'research_claims', ['workspace_id'], unique=False)
    op.create_table('research_claim_evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('support_level', sa.String(length=32), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['research_claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['research_evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'claim_id', 'evidence_id', name='uq_research_claim_evidence')
    )
    op.create_index(op.f('ix_research_claim_evidence_claim_id'), 'research_claim_evidence', ['claim_id'], unique=False)
    op.create_index(op.f('ix_research_claim_evidence_evidence_id'), 'research_claim_evidence', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_research_claim_evidence_workspace_id'), 'research_claim_evidence', ['workspace_id'], unique=False)
    op.create_table('research_review_findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=True),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('finding_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['research_claims.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evidence_id'], ['research_evidence.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['research_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['research_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_review_findings_claim_id'), 'research_review_findings', ['claim_id'], unique=False)
    op.create_index(op.f('ix_research_review_findings_evidence_id'), 'research_review_findings', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_research_review_findings_report_id'), 'research_review_findings', ['report_id'], unique=False)
    op.create_index(op.f('ix_research_review_findings_task_id'), 'research_review_findings', ['task_id'], unique=False)
    op.create_index(op.f('ix_research_review_findings_workspace_id'), 'research_review_findings', ['workspace_id'], unique=False)
    op.add_column('research_reports', sa.Column('report_status', sa.String(length=32), nullable=False))
    op.add_column('research_reports', sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_reports', 'validated_at')
    op.drop_column('research_reports', 'report_status')
    op.drop_index(op.f('ix_research_review_findings_workspace_id'), table_name='research_review_findings')
    op.drop_index(op.f('ix_research_review_findings_task_id'), table_name='research_review_findings')
    op.drop_index(op.f('ix_research_review_findings_report_id'), table_name='research_review_findings')
    op.drop_index(op.f('ix_research_review_findings_evidence_id'), table_name='research_review_findings')
    op.drop_index(op.f('ix_research_review_findings_claim_id'), table_name='research_review_findings')
    op.drop_table('research_review_findings')
    op.drop_index(op.f('ix_research_claim_evidence_workspace_id'), table_name='research_claim_evidence')
    op.drop_index(op.f('ix_research_claim_evidence_evidence_id'), table_name='research_claim_evidence')
    op.drop_index(op.f('ix_research_claim_evidence_claim_id'), table_name='research_claim_evidence')
    op.drop_table('research_claim_evidence')
    op.drop_index(op.f('ix_research_claims_workspace_id'), table_name='research_claims')
    op.drop_index(op.f('ix_research_claims_task_id'), table_name='research_claims')
    op.drop_index(op.f('ix_research_claims_report_id'), table_name='research_claims')
    op.drop_table('research_claims')
    # ### end Alembic commands ###
